In [58]:
import numpy as np 


e1 = np.array([0, 1, -1])
e2 = np.array([1, 1,  3])
e3 = np.array([2, 1,  0])

# e1 = np.array([1, 1, -1])
# e2 = np.array([2, -1,  1])
# e3 = np.array([0, -1,  -1])

dextro = np.dot(  np.cross(e1, e2), e3 ) 

if dextro > 0:
    print("El sistema es dextrógiro", dextro)
else:
    print("El sistema es lovegiro")

El sistema es dextrógiro 7


In [59]:

# Ae = b

A = np.stack(
    [ e1 / np.sqrt( np.dot(e1, e1) ) ,
      e2 / np.sqrt( np.dot(e2, e2) ) ,
      e3 / np.sqrt( np.dot(e3, e3) )
    ]   
)

b1 = np.array([1, 0, 0])
b2 = np.array([0, 1, 0])
b3 = np.array([0, 0, 1])


ep1 = np.linalg.inv(A) @ b1
ep2 = np.linalg.inv(A) @ b2
ep3 = np.linalg.inv(A) @ b3

In [60]:
print(ep1)
print(ep2)
print(ep3)

[-0.60609153  1.21218305 -0.20203051]
[-0.47380354  0.94760708  0.94760708]
[ 1.27775313 -0.31943828 -0.31943828]


In [68]:
ed1 = np.cross( e2, e3 ) / np.dot( e1, np.cross( e2, e3)  )
print(ed1)

[-0.42857143  0.85714286 -0.14285714]


In [69]:
np.dot(ep1, e1) / np.sqrt( np.dot(e1, e1) )

1.0